name: ZeZenithPlugin
main: de.db.ZeZenithPlugin
version: 1.1
author: YourN
description: A plugin to skip the night by voting.

commands:
  gn:
    description: Vote to skip the night.
    usage: /<command>
    aliases: [goodnight]
  zenith:
    description: Administration commands for the ZeZenithPlugin.
    usage: /<command> [help]
    permission: zenith.admin
    permission-message: You do not have permission to use this command.

permissions:
  zenith.admin:
    description: Allows access to all admin commands of the ZeZenithPlugin.
    default: op