name: ZeZenithPlugin
main: de.db.ZeZenithPlugin
version: 1.0.0
author: ZeBobbel
description: Ein Plugin, um die Nacht per Abstimmung zu 端berspringen.

commands:
  gn:
    description: Stimme daf端r ab, die Nacht zu 端berspringen.
    usage: /<command>
    aliases: [goodnight]
  zenith:
    description: Administrationsbefehle f端r das ZeZenithPlugin.
    usage: /<command> [help]
    permission: zenith.admin
    permission-message: Du hast keine Rechte, diesen Befehl zu nutzen.

permissions:
  zenith.admin:
    description: Erlaubt den Zugriff auf alle Admin-Befehle des ZeZenithPlugins.
    default: op